name: Daily Vacation Development Log

on:
  schedule:
    - cron: '30 20 * * *'  # Runs daily at 20:30 UTC (11:30 PM Ethiopia time)
  workflow_dispatch:  # Allows manual triggering

jobs:
  daily-log:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Setup log file structure
        run: |
          # Create the log file with header if it doesn't exist
          if [ ! -f VACATION_LOG.md ]; then
            echo "# 🏖️ Vacation Development Log" > VACATION_LOG.md
            echo "" >> VACATION_LOG.md
            echo "This log tracks daily development planning and progress during vacation." >> VACATION_LOG.md
            echo "" >> VACATION_LOG.md
            echo "## Daily Entries" >> VACATION_LOG.md
            echo "" >> VACATION_LOG.md
            echo "*Log started: September 24, 2025*" >> VACATION_LOG.md
            echo "" >> VACATION_LOG.md
          fi

      - name: Add daily entry
        run: |
          # Array of realistic development activities
          ACTIVITIES=(
            "Refactored component architecture for better performance"
            "Documented API endpoints and improved documentation"
            "Optimized database queries and indexing strategies"
            "Planned new feature implementation roadmap"
            "Reviewed code quality and implemented improvements"
            "Designed new user interface components"
            "Updated project dependencies and security patches"
            "Wrote unit tests for critical functionality"
            "Researched new technologies for implementation"
            "Improved error handling and user feedback systems"
            "Developed new database migration scripts"
            "Enhanced application security measures"
            "Created API documentation and examples"
            "Optimized frontend build process"
            "Implemented new data validation rules"
          )
          
          # Get a random activity
          RANDOM_INDEX=$(( RANDOM % ${#ACTIVITIES[@]} ))
          SELECTED_ACTIVITY="${ACTIVITIES[$RANDOM_INDEX]}"
          
          # Calculate vacation day number starting from TOMORROW (Sep 24)
          START_DATE="2025-09-24"  # ⚠️ Starts from tomorrow!
          CURRENT_DATE=$(date +%Y-%m-%d)
          DAYS=$(( ( $(date -d "$CURRENT_DATE" +%s) - $(date -d "$START_DATE" +%s) ) / 86400 + 1 ))
          
          # Only add entry if we're on or after start date
          if [ $DAYS -ge 1 ]; then
            echo "- **Vacation Day $DAYS**: $SELECTED_ACTIVITY. *($(date '+%Y-%m-%d'))*" >> VACATION_LOG.md
            echo "✅ Added entry: Vacation Day $DAYS - $SELECTED_ACTIVITY"
          else
            echo "⏸️  Not yet time to start logging (starts: $START_DATE)"
          fi

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add VACATION_LOG.md
          
          # Only commit if there are changes and we're past start date
          if git diff --staged --quiet; then
            echo "No changes to commit."
          else
            git commit -m "docs: vacation development notes for $(date +%Y-%m-%d)"
            git push
            echo "🚀 Successfully updated vacation log!"
          fi