name: Daily Vacation Development Log

on:
  schedule:
    - cron: '30 20 * * *'
  workflow_dispatch:

jobs:
  daily-log:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Setup log file
        run: |
          # Create log directory if needed
          mkdir -p logs
          
      - name: Add daily entry
        run: |
          # Simple date calculation that always works
          DAYS=$(( ( $(date +%s) - $(date -d "2025-09-24" +%s) ) / 86400 + 1 ))
          
          # Create simple log entry
          echo "Day $DAYS: Flutter development progress - $(date)" >> logs/vacation_log.txt
          echo "Added entry for day $DAYS"

      - name: Commit and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "docs: flutter progress update $(date +%Y-%m-%d)"
            git push
          fi